version: '3.8'

services:
  marketpostgres:
    image: postgres:12.0
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
  marketapp:
    build: './'
    image: marketapp:latest
    restart: always
    environment:
      DATABASE_URL: 'jdbc:postgresql://marketpostgres:5432/postgres'
    ports:
      - 80:8080
    depends_on:
      - marketpostgres