spring:
  freemarker:
    checkTemplateLocation: false
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  datasource:
    name: primaryDS
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      login-timeout: 120
      connection-timeout: 120000
      initialization-fail-timeout: -1
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    contexts: local
  cache:
    type: None
  jpa:
    properties:
      hibernate:
        synonyms: true
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        batch_fetch_style: DYNAMIC
        criteria:
          literal_handling_mode: BIND
        connection:
          includeSynonyms: true
          charSet: UTF-8
        jdbc:
          batch_size: 100
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  main:
    allow-bean-definition-overriding: true
    banner-mode: off

springdoc:
  packages-to-scan: com.yandex
  paths-to-match: "/**"